"""
Runs the whole pipeline and writes a processing report showing what happened to the
data at each stage.
    python src/run_all.py
Writes outputs/processing_report.md and outputs/processing_steps.png (plus everything
the individual scripts write).
"""
import subprocess
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.spatial import cKDTree

import multi_ride as m

SRC = m.BASE / "src"
OUT = m.BASE / "outputs"


def run(script):
    print(f"\n=== {script} ===")
    subprocess.run([sys.executable, str(SRC / script)], check=True, cwd=m.BASE)


def stage_counts(ref, tree):
    rows = []
    for folder, rid, direction in m.RIDES:
        acc, loc_all, tm = m.read(folder)
        loc_raw = pd.read_csv(m.RAW / folder / "Location.csv")
        rate = 1 / acc.t.diff().median()
        r = dict(ride=rid, direction=direction, accel_hz=round(rate, 1),
                 accel_samples_raw=len(acc), gps_fixes_raw=len(loc_raw),
                 gps_fixes_kept=len(loc_all), pauses=int((tm.event == "PAUSE").sum()))
        if rate < 50:
            r["status"] = "excluded: accelerometer < 50 Hz (GPS used as reference)"
            rows.append(r)
            continue
        acc["a"] = m.vertical_vibration(acc)
        for c in ["lat", "lon", "v"]:
            acc[c] = np.interp(acc.t, loc_all.t, loc_all[c])
        edge = m.EDGE_OVERRIDE.get(rid, m.EDGE_S)
        keep = np.ones(len(acc), bool)
        for ev, et in zip(tm.event, tm["experiment time"]):
            keep &= ~(((acc.t >= et) & (acc.t < et + edge)) if ev == "START"
                      else ((acc.t > et - edge) & (acc.t <= et))).to_numpy()
        a2 = acc[keep]
        d, _ = tree.query(m.xy(a2.lat, a2.lon))
        a3 = a2[d <= m.MATCH_M]
        r.update(after_trim=len(a2), after_map_match=len(a3),
                 moving_ge_1_5ms=int((a3.v >= m.MIN_SPEED).sum()),
                 status="used")
        rows.append(r)
    return pd.DataFrame(rows)


def steps_figure(ref, tree):
    """Raw 3-axis -> vertical vibration -> 50 m roughness, for one stretch of rp5."""
    acc, loc, _ = m.read("rp5")
    acc["a"] = m.vertical_vibration(acc)
    for c in ["lat", "lon", "v"]:
        acc[c] = np.interp(acc.t, loc.t, loc[c])
    b = pd.read_parquet(m.PROCESSED / "samples_binned.parquet")
    b = b[(b.ride_id.str.startswith("rp5")) & (b.seg == "S4")].sort_values("bin")
    d, i = tree.query(m.xy(acc.lat, acc.lon))
    s4 = acc[(ref.seg.to_numpy()[i] == "S4") & (d <= m.MATCH_M)]
    w = s4[(s4.t >= s4.t.min() + 60) & (s4.t <= s4.t.min() + 90)]
    fig, ax = plt.subplots(3, 1, figsize=(12, 9))
    for c in ["ax", "ay", "az"]:
        ax[0].plot(w.t, w[c], lw=.6, label=c)
    ax[0].set_title("1. Raw accelerometer, 3 axes (includes gravity), 30 s on Library–Core 5, rp5")
    ax[0].set_ylabel("m/s²"); ax[0].legend(fontsize=8, loc="upper right")
    ax[1].plot(w.t, w.a, lw=.6, c="k")
    thr = 10
    ax[1].axhline(thr, ls="--", c="tab:red", lw=.8); ax[1].axhline(-thr, ls="--", c="tab:red", lw=.8)
    ax[1].set_title("2. Vertical vibration (gravity removed, orientation-independent); dashed = bump threshold")
    ax[1].set_ylabel("m/s²"); ax[1].set_xlabel("ride time (s)")
    ax[2].bar(b.bin * 50, b.roughness, width=45, color="tab:orange")
    ax[2].set_title("3. Roughness per 50 m bin (RMS vertical ÷ speed), whole Library–Core 5 segment, rp5")
    ax[2].set_xlabel("distance along segment (m)"); ax[2].set_ylabel("roughness")
    fig.tight_layout(); fig.savefig(OUT / "processing_steps.png", dpi=120)


def main():
    run("multi_ride.py")
    run("locate_photos.py")
    run("survey_summary.py")
    run("build_extras.py")

    ref = m.build_reference()
    tree = cKDTree(m.xy(ref.lat, ref.lon))
    st = stage_counts(ref, tree)
    steps_figure(ref, tree)

    seg = pd.read_csv(m.PROCESSED / "segment_summary.csv")
    hs = pd.read_csv(m.PROCESSED / "hotspots.csv")
    b = pd.read_parquet(m.PROCESSED / "samples_binned.parquet")
    lab = pd.read_csv(m.PROCESSED / "photo_labels.csv")
    spots = lab.drop_duplicates(["lat", "lon"])

    md = ["# Processing report", "",
          "Generated by `python src/run_all.py`. Every number below is recomputed from `data/raw/`.", "",
          "## Per-ride data flow", "",
          "Stages: raw samples → trimmed (15 s around starts/pauses; 4 s on rp6) → map-matched "
          "(≤ 30 m from reference route) → moving (≥ 1.5 m/s).", "",
          st.to_markdown(index=False), "",
          "## Outputs", "",
          f"- 50 m bins: {b.groupby(['seg', 'bin']).ngroups} canonical bins, {len(b)} ride×bin rows "
          f"from {b.ride_id.nunique()} rides",
          f"- Bump hotspots: {len(hs)} total, {(hs.status == 'confirmed').sum()} confirmed in ≥ 2 rides",
          f"- Photos: {len(lab)} photos at {len(spots)} spots; {(spots.hotspot_dist_m <= 25).sum()} "
          f"within 25 m of a hotspot, {(spots.hotspot_status == 'confirmed').sum()} at confirmed hotspots",
          "", "## Segment roughness", "",
          seg[["segment", "rides", "mean_roughness", "std_across_rides", "length_m",
               "confirmed_hotspots"]].to_markdown(index=False), "",
          "![processing steps](processing_steps.png)", ""]
    (OUT / "processing_report.md").write_text("\n".join(md))
    print("\n".join(md))


if __name__ == "__main__":
    main()
